name = "VSSystems"
uuid = "153bda20-02c3-486f-9572-3b440292a967"
authors = ["Alessandro Colotti <alessandro.colotti@ls2n.fr> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
